### ISSUE TITLE
you removed 1.18.1 docs i creating mod for 1.18.1............................

### ISSUE THREAD

**Issue by iocmet** [Nekoyue/ForgeJavaDocs-NG#2]

**Comment by Nekoyue** [comment]
1.18.1 is now added back in ecf45d308c768cf03b61b40bc11e2923882b9a32. It will stay there until the next recommended build of 1.18.2 come out.

**Comment by iocmet** [comment]
ok thanks

**Comment by Nekoyue** [comment]
no problem, happy developing!
