### ISSUE TITLE
is there one in the making for neoforge

### ISSUE THREAD

**Issue by Thunderrock424242** [Nekoyue/ForgeJavaDocs-NG#5]
it would be amazing to have a neoforge one

**Comment by Nekoyue** [comment]
Lots happened last year in the forge community, wow! I am taking a look right now. There shouldn't be a significant difference in how the javadoc is generated.

**Comment by Nekoyue** [comment]
It is now up and live in 56e85342b0cacbc72f4f0bf47c09db30f34a1c0c 
https://nekoyue.github.io/ForgeJavaDocs-NG/javadoc/1.20.6-neoforge/

**Comment by Thunderrock424242** [comment]
Yay ty
